### ISSUE TITLE
功能调用失败，请检查输入的功能序号

### ISSUE THREAD

**Issue by 2773328341** [liuyunfz/chaoxing_tool#100]
我输入了序号，获取章节中就弹出，功能调用失败，请检查输入的功能序号
![7896fa789ee625f0da6c6ab6cf2a7c1](https://github.com/liuyunfz/chaoxing_tool/assets/94550603/914b003d-2b8e-42c0-ba1b-1fda2386d4f2)

**Comment by liuyunfz** [comment]
该问题已修复，最新的源代码与release都已更新，还烦请再试一次

**Comment by 2773328341** [comment]
你好，我试了新版的，可以获取任务点了。但是还会功能调用失败，请检查输入的功能序号
![image](https://github.com/liuyunfz/chaoxing_tool/assets/94550603/7051a9f9-83e5-4356-af18-22f1477ea376)

**Comment by 2773328341** [comment]
你好，我试了新版的，可以获取任务点了。但是还会功能调用失败，请检查输入的功能序号
![image](https://github.com/liuyunfz/chaoxing_tool/assets/94550603/a96a4991-45e8-4977-9673-62faf1102a2b)

**Comment by wxm78** [comment]
您好，作者我也出现了同样的情况。
![image](https://github.com/liuyunfz/chaoxing_tool/assets/81608551/c84063af-192d-448a-9dea-6fe0041cd07c)

**Comment by liuyunfz** [comment]
初步看了一下，我这边也会有课程出现该问题，原因是该课程开启了结课模式，所以无法进行完成。烦请核查一下是否是同样的问题，是的话之后会进行判断跳过

**Comment by liuyunfz** [comment]
该问题已在最新的commit中进行了修复，烦请再测试一下
https://github.com/liuyunfz/chaoxing_tool/commit/a1bd6dd22f35391b208d5c535573038b09490c9b

**Comment by wxm78** [comment]
> 该问题已在最新的commit中进行了修复，烦请再测试一下 [a1bd6dd](https://github.com/liuyunfz/chaoxing_tool/commit/a1bd6dd22f35391b208d5c535573038b09490c9b)
感谢作者，可以正常运行了。
![image](https://github.com/liuyunfz/chaoxing_tool/assets/81608551/02c596a6-d3a6-4051-b528-2e57b7788d8a)

**Comment by 2773328341** [comment]
> 该问题已在最新的commit中进行了修复，烦请再测试一下 [a1bd6dd](https://github.com/liuyunfz/chaoxing_tool/commit/a1bd6dd22f35391b208d5c535573038b09490c9b)

可以刷取了，但是刷到一半还是会报错，咋办
![image](https://github.com/liuyunfz/chaoxing_tool/assets/94550603/6bd7a801-7ddb-4b52-a632-fca20390641e)

**Comment by liuyunfz** [comment]
> > 该问题已在最新的commit中进行了修复，烦请再测试一下 [a1bd6dd](https://github.com/liuyunfz/chaoxing_tool/commit/a1bd6dd22f35391b208d5c535573038b09490c9b)
> 
> 可以刷取了，但是刷到一半还是会报错，咋办 ![image](https://user-images.githubusercontent.com/94550603/246580554-6bd7a801-7ddb-4b52-a632-fca20390641e.png)

想问一下该课程进入是否有啥校验，比如说要人脸识别这种

**Comment by liuyunfz** [comment]
> > 该问题已在最新的commit中进行了修复，烦请再测试一下 [a1bd6dd](https://github.com/liuyunfz/chaoxing_tool/commit/a1bd6dd22f35391b208d5c535573038b09490c9b)
> 
> 可以刷取了，但是刷到一半还是会报错，咋办 ![image](https://user-images.githubusercontent.com/94550603/246580554-6bd7a801-7ddb-4b52-a632-fca20390641e.png)

就是如下这些
![image](https://github.com/liuyunfz/chaoxing_tool/assets/46259392/cea137d9-b5ce-4a88-86b2-0fe10f6d9ccb)

**Comment by 2773328341** [comment]
> > > 该问题已在最新的commit中进行了修复，烦请再测试一下 [a1bd6dd](https://github.com/liuyunfz/chaoxing_tool/commit/a1bd6dd22f35391b208d5c535573038b09490c9b)
> > 
> > 
> > 可以刷取了，但是刷到一半还是会报错，咋办![image](https://user-images.githubusercontent.com/94550603/246580554-6bd7a801-7ddb-4b52-a632-fca20390641e.png)
> 
> 就是如下这些 ![image](https://user-images.githubusercontent.com/46259392/246672182-cea137d9-b5ce-4a88-86b2-0fe10f6d9ccb.png)

没有开人脸识别，其他的我也不太清楚。我试了新版的，还是有这样的问题。
![image](https://github.com/liuyunfz/chaoxing_tool/assets/94550603/7be2842e-0d82-43de-921f-ad0d0312a0da)

**Comment by C315703603** [comment]
问题同上，依旧是有的课刷取途中会有[功能调用失败，请检查输入的功能序号]的情况
![% U KW7TQS5VV7})AXAX2W](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/291eff54-1a9b-47f0-a3a3-35cc062ba4af)
该课刚开课。而且显示正常完成的课程实际上并没有刷取上
![3E4)4 S}HM{9 5J9VAQQG9X](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/33a93413-8852-47af-9a8b-ea73dca6ddd2)
![$X5DE5` 8`{`Z~MPB~2W9~1](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/de27d425-db68-4fe8-a1ef-8f8d3806120e)
怀疑是没有等时长刷取，但是更改config.yml中等时长刷取后程序依旧还是立即完成，是哪里设置的不对吗？
![2SCBOVJ3K{5A2O_2K5UI QE](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/c152af05-cd51-4bb5-907b-6b8bdb361bb1)

**Comment by liuyunfz** [comment]
> 问题同上，依旧是有的课刷取途中会有[功能调用失败，请检查输入的功能序号]的情况 ![% U KW7TQS5VV7})AXAX2W](https://user-images.githubusercontent.com/103497700/264503356-291eff54-1a9b-47f0-a3a3-35cc062ba4af.png) 该课刚开课。而且显示正常完成的课程实际上并没有刷取上 ![3E4)4 S}HM{9 5J9VAQQG9X](https://user-images.githubusercontent.com/103497700/264503697-33a93413-8852-47af-9a8b-ea73dca6ddd2.png) ![FQEKYK1_M9KE8$2BVNM2@T7](https://user-images.githubusercontent.com/103497700/264503886-57995930-5314-4fdc-bc1b-997713454a6c.png) ![$X5DE5 8{`ZMPB2W9~1](https://user-images.githubusercontent.com/103497700/264503706-de27d425-db68-4fe8-a1ef-8f8d3806120e.png) 怀疑是没有等时长刷取，但是更改config.yml中等时长刷取后程序依旧还是立即完成，是哪里设置的不对吗？ ![2SCBOVJ3K{5A2O_2K5UI QE](https://user-images.githubusercontent.com/103497700/264503782-c152af05-cd51-4bb5-907b-6b8bdb361bb1.png)

您好，很抱歉给你带来不好的体验。从你提供的图片中，里面的url直观的显示了antiSpider，也就是反爬虫的验证系统。应该是最近超星系统有所更新，所以导致程序不一定能正常生效。
另外你提供的最后一张图似乎是程序并没有读取到任务点，如果是想要完成测验的话本程序是不支持的

**Comment by C315703603** [comment]
辛苦大大了，不过我最后不是刷测验的是打算等时长刷取视频的，但是好像并没有识别到视频的任务点，我以为是我最后设置的不正确。

**Comment by liuyunfz** [comment]
本issue中原涉及问题已解决。附带的反爬验证已在[ff63cdba644bcdd4e1e97f68c52304c2bf0ff706](https://github.com/liuyunfz/chaoxing_tool/commit/ff63cdba644bcdd4e1e97f68c52304c2bf0ff706)后进行了全局延迟功能添加以及修复任务点的读取。
目前留存的可能出现的部分任务点的403状态读取错误合并至https://github.com/liuyunfz/chaoxing_tool/issues/103 ，并对此issue进行关闭。
