### ISSUE TITLE
功能调用错误提示AttributeError: 'str' object has no attribute 'xpath'

### ISSUE THREAD

**Issue by xiaonian233** [liuyunfz/chaoxing_tool#102]
功能调用错误提示AttributeError: 'str' object has no attribute 'xpath'
![image](https://github.com/liuyunfz/chaoxing_tool/assets/21072615/1b30d6d4-8d1c-43b6-9919-69948dda76a2)
无论是源码运行还是可执行文件运行都是这个结果
不知道为什么
Python 64bit 3.10

**Comment by liuyunfz** [comment]
看起来是读取章节目录出现了错误，能否将该课程目录的源代码贴上来呢，链接应该是以https://mooc2-ans.chaoxing.com/mooc2-ans/mycourse/studentcourse打头的

**Comment by xiaonian233** [comment]
[1.txt](https://github.com/liuyunfz/chaoxing_tool/files/12508853/1.txt)
https://mooc2-ans.chaoxing.com/mooc2-ans/mycourse/studentcourse?courseid=236261491&clazzid=80525693&cpi=158455516&ut=s&t=1693794000
保存在1.txt中了

**Comment by C315703603** [comment]
![S~_A _F(}WA@XPL KDS~1G4](https://github.com/liuyunfz/chaoxing_tool/assets/103497700/fd2da69c-b0e4-4130-b597-f3d6e705e41c)
同上

**Comment by liuyunfz** [comment]
您好，该问题已在最新的commit中修复了，还烦请测试一下

**Comment by liuyunfz** [comment]
您好，该问题已在最新的commit中修复，还烦请测试一下

**Comment by xiaonian233** [comment]
> 您好，该问题已在最新的commit中修复，还烦请测试一下

目前看来没有什么问题了，但是建议在章节处理那里加入分批处理即一次性处理几章什么的，否则容易触发反爬

**Comment by Hentai02** [comment]
我也出现了这个问题
![image](https://github.com/liuyunfz/chaoxing_tool/assets/54672936/4168dafd-7627-4520-b386-1d6a44f15877)

**Comment by liuyunfz** [comment]
> 我也出现了这个问题
> ![image](https://user-images.githubusercontent.com/54672936/266300065-4168dafd-7627-4520-b386-1d6a44f15877.png)

源代码已经更新了，release还需要过段时间才会更新
