### ISSUE TITLE
这个是不是bug？

### ISSUE THREAD

**Issue by monkey5689** [liuyunfz/chaoxing_tool#104]
![屏幕截图 2023-09-14 184047](https://github.com/liuyunfz/chaoxing_tool/assets/79742234/f5b1eef4-53bf-404b-9398-be3cb60f2f63)
这是怎么回事？

**Comment by liuyunfz** [comment]
这个问题已知且修复了，是由于超星更新了网页结构导致的。目前最新的release还没更新，可以先用源代码或者等等

**Comment by monkey5689** [comment]
源代码用pyinstaller打包后运行，为什么获取课程列表之后会自动退出程序？需要的第三方包都已经安装了。

**Comment by liuyunfz** [comment]
你好，已临时发布release https://github.com/liuyunfz/chaoxing_tool/releases/tag/v2.1.1
您曾经提及的打包后无法运行的问题是程序是动态加载，需要将以下文件移至可执行文件的同级目录中
- classes 文件夹
- functions 文件夹
- config.yml 文件
