### ISSUE TITLE
错误202

### ISSUE THREAD

**Issue by monkey5689** [liuyunfz/chaoxing_tool#106]
有些任务点会报错误202
![mmexport1695012277205](https://github.com/liuyunfz/chaoxing_tool/assets/79742234/d2504986-fbeb-4ecf-b843-670577c48575)
模式:随机延迟多线程，等时长刷

**Comment by monkey5689** [comment]
现在单线程也会这样

**Comment by liuyunfz** [comment]
202触发反爬，可以把配置里的延时设置高一点
