### ISSUE TITLE
检测到不支持任务节点的workid

### ISSUE THREAD

**Issue by gdfhgdfhdfggvbd** [liuyunfz/chaoxing_tool#111]
[](url)
![QQ图片20231017162607](https://github.com/liuyunfz/chaoxing_tool/assets/148199248/c9f42ad7-ec1c-422c-8c53-d569cae819fb)

**Comment by liuyunfz** [comment]
这不是bug，程序检测到了章节测验类型的任务点，会自动跳过并发出该error。
程序不支持也不打算支持章节测验任务点的完成
