### ISSUE TITLE
更新通告

### ISSUE THREAD

**Issue by liuyunfz** [liuyunfz/chaoxing_tool#115]
由于本人近段时间在处理学业，所以较少有时间进行项目维护。
如果您在使用本项目时遇到可以改进的点，或逻辑优化的点，可以提出pr。亦或者提出issue，但会较晚响应。
如果您遇到了导致程序无法正常使用的bug，请您提出新的issue描述相关问题。最好是能够添加我的联系方式并提供出错环境，方便调试复现。也欢迎您随时提出pr，我会每周不定期进行统一处理。
以下为我的联系方式：
QQ 957843164
邮箱 ly@6yfz.cn

感谢各位对开源项目的贡献支持

**Comment by xjw008** [comment]
超星还是无法使用呀
