### ISSUE TITLE
失效了 不能用了

### ISSUE THREAD

**Issue by yfdhd1228** [liuyunfz/chaoxing_tool#123]
2024-04-27 20:19:33.203 | ERROR | utils:doPost:74 - Post Url https://passport2.chaoxing.com/fanyalogin Error
 HTTPSConnectionPool(host='passport2.chaoxing.com', port=443): Max retries exceeded with url: /fanyalogin (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
20:19:33 | ERROR | 'NoneType' object has no attribute 'status_code'
<img width="857" alt="图片1" src="https://github.com/liuyunfz/chaoxing_tool/assets/97522344/e34e293c-c733-450c-9617-4808f0e627e1">

**Comment by liuyunfz** [comment]
你好，出现这个问题可能是你启动了VPN软件。或者你可以将VPN软件改为PAC模式。

**Comment by yfdhd1228** [comment]
> 你好，出现这个问题可能是你启动了VPN软件。或者你可以将VPN软件改为PAC模式。

好了好了 太厉害了！大佬大佬（顶级膜拜）
