### ISSUE TITLE
MAIN无法在WIN64环境中打开

### ISSUE THREAD

**Issue by Ye-leng** [liuyunfz/chaoxing_tool#124]
来自电脑中无编程环境的非相关领域使用者。
下载后发现，代码包中只有关于WIN32系统环境的相关代码，WIN64系统环境的似乎没有，所以导致WIN64系统的使用者无法使用您开发的软件。
祝您生活愉快。

**Comment by liuyunfz** [comment]
你好，最近的版本使用了新版的pyinstaller，您可以试试有没有解决该问题。由于我这边未能成功复现且您较长时间未回复，故关闭本issue，如果你还有问题欢迎重新打开
