### ISSUE TITLE
无法登录

### ISSUE THREAD

**Issue by 1642414488** [liuyunfz/chaoxing_tool#125]
<img width="607" alt="b873c88d0d17ddfe81546983c761643" src="https://github.com/liuyunfz/chaoxing_tool/assets/20734339/06f0d769-22ea-4633-99b5-404dc39b7772">

**Comment by liuyunfz** [comment]
这个老问题了，每隔一段时间就有人提出。把vpn关掉或者设置成pac模式就行了
