### ISSUE TITLE
学习时长

### ISSUE THREAD

**Issue by wxm78** [liuyunfz/chaoxing_tool#13]
![屏幕截图 2021-11-17 105107](https://user-images.githubusercontent.com/81608551/142121294-90f18a78-43dd-4350-867c-faea054bb05a.png)

**Comment by liuyunfz** [comment]
您好，相关问题已在最新commit中修复（还烦请您再次尝试一下）。如果您用的是release，稍后我将会编译最新的版本提交，您可以自行下载。

**Comment by 2773328341** [comment]
好滴好滴 我用的release 我等会再试试

**Comment by liuyunfz** [comment]
您好，release已更新

**Comment by 2773328341** [comment]
可以啦可以啦 牛的牛的

**Comment by wxm78** [comment]
感谢大佬，辛苦了。
