### ISSUE TITLE
输入不了密码怎么办 输入完手机号后密码输不了

### ISSUE THREAD

**Issue by 2773328341** [liuyunfz/chaoxing_tool#14]

**Comment by southcat** [comment]
python版本多少   我在3.10不提示输入密码 回车也没有 可以先把60行的getpass.getpass换成input

**Comment by liuyunfz** [comment]
您好，请详阅软件功能介绍第二条
![image](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png)
如果不是这个问题，也烦请您提供更多具体信息

**Comment by southcat** [comment]
> 您好，请详阅软件功能介绍第二条 ![image](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png) 如果不是这个问题，也烦请您提供更多具体信息

![image](https://user-images.githubusercontent.com/32999518/142387389-5c5c2ecd-bc5c-46b9-b7d2-3f2601804fc8.png)
如上图 没有输入密码的提示 现在进行输入的话是直接显示出来的 python3.10  我直接新创建了一个文档使用了getpass运行之后是直接会报错的 可能是python3.10存在这个问题

**Comment by 2773328341** [comment]
> python版本多少 我在3.10不提示输入密码 回车也没有 可以先把60行的getpass.getpass换成input
搞定了 原来是密码隐藏了

**Comment by 2773328341** [comment]
> [， ![image](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png) ](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png)

**Comment by 2773328341** [comment]
> [， ![image](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png) ](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.p

> 您好，请详阅软件功能介绍第二条 ![image](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png) 如果不是这个问题，也烦请您提供更多具体信息

刷学习视频时长会闪退怎么办

**Comment by liuyunfz** [comment]
> > [， ![image](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png) ](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.p
> 
> > 您好，请详阅软件功能介绍第二条 ![image](https://user-images.githubusercontent.com/46259392/142386613-8c303fbd-64c7-40fc-8793-74b2b8138f4b.png) 如果不是这个问题，也烦请您提供更多具体信息
> 
> 刷学习视频时长会闪退怎么办

您好，如果您出现的是 https://github.com/liuyunfz/chaoxing_tool/issues/13 类似的问题，那么将会在最新的commit里得到修复，请您耐心等待。
