### ISSUE TITLE
要刷的视频一多了就刷不了了

### ISSUE THREAD

**Issue by fuhua666** [liuyunfz/chaoxing_tool#16]
我的军事理论要刷144个视频，咋都刷不了。
![Uploading 图片.png…]()

**Comment by liuyunfz** [comment]
你好，不知道是不是我本地的网络原因，你上传的图片我看不到。希望您能提供更加详细的信息，比如报错信息。
按照软件的流程，会扫描一遍整个课程，然后在扫描完毕后对所有视频任务点进行统一处理，由用户选择是立即完成还是同倍速完成。
另外，也烦请您检查使用的是否为最新的代码版本或是1.5.1release版本

**Comment by fuhua666** [comment]
就是他扫描一个一个扫描我视频的时候，还没扫描完就报错了

**Comment by liuyunfz** [comment]
麻烦贴一下报错的具体消息，我好看看是什么问题。

**Comment by fuhua666** [comment]
![Uploading IMG_20220317_211621.jpg…]()

**Comment by fuhua666** [comment]
你要是还看不见图片的话，你给我个邮箱，我发你邮箱

**Comment by liuyunfz** [comment]
其实你可以直接复制直接贴文字信息的。
或者麻烦发至：[ly@6yfz.cn](mailto:ly@6yfz.cn)

**Comment by liuyunfz** [comment]
相关内容已私下解决，相关BUG已在[e0ec85d](https://github.com/liuyunfz/chaoxing_tool/commit/e0ec85d1c338c316e91b5623d6b77ddf7af72bd6) 修复，故关闭此issue
