### ISSUE TITLE
刷取视频时长功能出现异常

### ISSUE THREAD

**Issue by t0mmycoding** [liuyunfz/chaoxing_tool#18]
![图片](https://user-images.githubusercontent.com/92618753/159154075-b920bf8e-a3f5-4162-afe5-9a0004e02461.png)

**Comment by liuyunfz** [comment]
你好，请问是只有这个课程出现了问题还是所有课程都出现了该问题呢？是之前可以正常刷，但是现在不行了，还是一直都不行呢？如果是检测异常的话应该会是通知那边有消息的

**Comment by t0mmycoding** [comment]
今天我用js脚本刷课后习题的时候，也出现了403错误。就是你需要返回之前的页面，然后再进行操作，又就可以了。然后我用软件刷课的时候刷时长，后面也报403。再后来我把有个一个结课的课程删了之又不报错了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 刷视频时长好像被检出异常了 (Issue #18)





 
你好，请问是只有这个课程出现了问题还是所有课程都出现了该问题呢？是之前可以正常刷，但是现在不行了，还是一直都不行呢？如果是检测异常的话应该会是通知那边有消息的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by t0mmycoding** [comment]
好像也一直在刷一个视频
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月20日(星期天) 下午4:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 刷视频时长好像被检出异常了 (Issue #18)





 
你好，请问是只有这个课程出现了问题还是所有课程都出现了该问题呢？是之前可以正常刷，但是现在不行了，还是一直都不行呢？如果是检测异常的话应该会是通知那边有消息的
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by liuyunfz** [comment]
你好，既然错误并不是100%发生，那就不是代码的问题了。也就更不属于检测出异常的范畴了，为了防止大家造成不必要的恐慌，我就关闭此issue了。针对已结束的课程，https://github.com/liuyunfz/chaoxing_tool/issues/7 曾提到无法正确识别课程内容，考虑到状态特殊性，这个bug我暂时也觉得没有修复的必要。
如果您仍然觉得这个问题干扰了你的正常刷课使用，也欢迎您再次打开此issue，并提供一些更具体的消息供我参考。再次感谢

**Comment by fuhua666** [comment]
他这个问题我也遇到了哎，应该是有问题的。一模一样的问题

**Comment by liuyunfz** [comment]
既然不止一人遇到了本问题，那么我就再次打开此issue。类似的错误在 https://github.com/liuyunfz/chaoxing_tool/issues/20 中也曾出现过，我在最新的 https://github.com/liuyunfz/chaoxing_tool/commit/cbf47c72e00d74eb000840713b43ea5915427e41 中修复了该问题，如果你们用的不是最新版，可以尝试测试一下这个新版本，如果你们需要可执行文件，那么可以从 `https://liuyunfz.lanzouf.com/i5nbO02nqlmf` 下载得到。
期待你们的回复反馈，感谢

**Comment by liuyunfz** [comment]
经过测试，在我这边的复现情况皆出现在已结课的课程中。由于已结课的课程不允许再完成任务，故出现了以上错误。同时该报错也不影响其他正常课程的时长刷取，故修复级别不高。
烦请您核对自己报错课程的情况，如果和我的情况不一样，也希望您能提供更多信息，再次感谢。

**Comment by fuhua666** [comment]
课程没有问题的，而且是老师让我们自己学习的。我听有个大佬说是有的课程用的是超星的新接口导致超星的返回值错误，所以刷不上。我用的也是您最新的代码。

**Comment by liuyunfz** [comment]
已私下取得联系，在 https://github.com/liuyunfz/chaoxing_tool/commit/62024887dbe937c05dacd653d4b3170a45249aef 版本中进行了修复尝试，并在本地测试成功。故关闭此issue，如有问题请再次打开
