### ISSUE TITLE
输入手机号后无反响

### ISSUE THREAD

**Issue by Fengzidalaoban** [liuyunfz/chaoxing_tool#2]
输入手机号后没有反应

**Comment by liuyunfz** [comment]
感谢您的反馈，但可惜的是我并没有复现出该情况。首先请和我确认您使用的是release中的可执行文件还是源代码中的py文件。
其次，你是在输入手机号后没有发生反应还是在输入密码时没有反应。如果是前者的话请检查你是否有按“回车键”确认；如果是后者的话请检查你的网络设置，或者尝试手动浏览器访问超星（学习通）的相关网站查看是否有异常。
如果以上办法都没能解决你的问题，那么也烦请你与我进行联系，以便我更好的了解相关的情况并为你解决问题。

**Comment by Fengzidalaoban** [comment]
cmd 运行后 正常输入手机号，弹出密码框后无法输入密码
无参数&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liuyunfz"<notifications@github.com&gt;; 
发送时间: 2020年12月16日(星期三) 下午3:28
收件人: "liuyunfz/chaoxing_tool"<chaoxing_tool@noreply.github.com&gt;; 
抄送: "深井#"<2524210044@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liuyunfz/chaoxing_tool] 输入手机号后无反响 (#2)





 
感谢您的反馈，但可惜的是我并没有复现出该情况。首先请和我确认您使用的是release中的可执行文件还是源代码中的py文件。
 其次，你是在输入手机号后没有发生反应还是在输入密码时没有反应。如果是前者的话请检查你是否有按“回车键”确认；如果是后者的话请检查你的网络设置，或者尝试手动浏览器访问超星（学习通）的相关网站查看是否有异常。
 如果以上办法都没能解决你的问题，那么也烦请你与我进行联系，以便我更好的了解相关的情况并为你解决问题。

**Comment by liuyunfz** [comment]
如果您要表达的是你在键盘中键入字母或数字时并未在屏幕当中显示，那么这其实是正常的。如果您曾用过Linux或许就会知道，这是一种为了保护使用者安全的措施。虽然您输入了值，屏幕中并未显示，但其实它已经输入进去了，你只需要像往常一样正确的输入密码，然后按回车就行了。同样的，如果你不小心输入了一个字符，按backspace也同样可以正常的删除一个字符。唯一不同的只是这一切你都看不到，无法得到反馈。

**Comment by Fengzidalaoban** [comment]
问题1：
学习通视频下方有文本类型的不会秒视频
2：视频有多个的时候不会秒全






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 下午3:36
收件人:&nbsp;"liuyunfz/chaoxing_tool"<chaoxing_tool@noreply.github.com&gt;;
抄送:&nbsp;"深井#"<2524210044@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 输入手机号后无反响 (#2)





 
如果您要表达的是你在键盘中键入字母或数字时并未在屏幕当中显示，那么这其实是正常的。如果您曾用过Linux或许就会知道，这是一种为了保护使用者安全的措施。虽然您输入了值，屏幕中并未显示，但其实它已经输入进去了，你只需要像往常一样正确的输入密码，然后按回车就行了。同样的，如果你不小心输入了一个字符，按backspace也同样可以正常的删除一个字符。唯一不同的只是这一切你都看不到，无法得到反馈。

**Comment by liuyunfz** [comment]
很抱歉给您带来这样的体验。不过我并不太了解您出现问题的具体情况，因为账号的限制，我目前只能从我的课程中获取具体视频的类型从而进行处理判断，所以才可能会导致了并不完全通用的问题。

首先是你提出的第一点，我并不太了解。就我个人测试的情况来说，如果视频出现在了第二页，即第一页是文本，第二页才是视频，会出现无法完成的情况。
![Snipaste_2020-12-16_18-10-14](https://user-images.githubusercontent.com/46259392/102334721-f9fcc200-3fc9-11eb-8eda-3a75e1edb9cc.png)
即以上这种情况，不知道是否是你所指出的这种。如果不是，希望您能附上截图，以便我能更好的知道如何修复。

然后是针对你说的第二点。如果符合视频处于第一页，应该不会出现视频任务未完成的情况。多个视频虽然由于我现在并未加入多线程，所以导致速度可能会比较慢，但稳定性应该是没有问题的。希望您能确认下未完成的视频是否属于“直播”类型，判断的依据是进度条的时间显示为负值。

**Comment by liuyunfz** [comment]
如果您出现的是我说的那种情况，即无法完成不处于第一页的视频任务。那么我刚才的更新已经修复了这个问题(仅更新了源代码文件，并未更新release)，至于其他类型的任务节点，也都在日程中，请您静候我的更新。如果你实在等不及也可以先和我独自进行联系，因为我已经完成了部分的功能书写，只是尚未实装。
如果关于视频类型还有其他问题，也欢迎通过qq，微信等方式和我更便捷的进行交流。
介于此issue的标题所描述的问题已经解决，我将关闭这个issue，请你悉知。
不过您在此issue下继续回复的内容，我还是会收到通知并对你进行回复。
