### ISSUE TITLE
超星似乎更换了API接口

### ISSUE THREAD

**Issue by hongzao0316** [liuyunfz/chaoxing_tool#20]
像这样：
课程读取完成，共有38个章节可一键完成
num: 0
https://mooc1-2.chaoxing.com/knowledge/cards?clazzid=50846179&courseid=207533891&knowledgeid=225475039&num=0&ut=s&cpi=105990630&v=20160407-1 error
num: 0
https://mooc1-2.chaoxing.com/knowledge/cards?clazzid=50846179&courseid=207533891&knowledgeid=225474887&num=0&ut=s&cpi=105990630&v=20160407-1 error
num: 1
num: 0
https://mooc1-2.chaoxing.com/knowledge/cards?clazzid=50846179&courseid=207533891&knowledgeid=225474900&num=0&ut=s&cpi=105990630&v=20160407-1 error
num: 1
num: 0

**Comment by SongZihui-sudo** [comment]
的确是，我也是前些天还可以，但是这几天就不行了。

**Comment by liuyunfz** [comment]
你好，经过我的测试，似乎是获取视频信息（时长，token等）的接口出现了问题，不过并不是接口更换了，而是额外添加了headers参数校验。最新的版本已经经过了我的本地测试，如果方便的话也烦请你测试一下，如果正常的话就关闭这个issue吧，如果还有问题也麻烦你继续在下面评论。给你带来的不便，再次感谢。
考虑到您可能使用的是release版本，这边也有一个临时编译的可执行文件`https://liuyunfz.lanzouf.com/i5nbO02nqlmf`

**Comment by 3str56** [comment]
好像不管用了

**Comment by SongZihui-sudo** [comment]
可以了
