### ISSUE TITLE
无法一键完成

### ISSUE THREAD

**Issue by FASUZO** [liuyunfz/chaoxing_tool#21]
![image](https://user-images.githubusercontent.com/77849230/162566485-c7931045-e5d8-44bc-9448-70eeb3f2053e.png)

**Comment by liuyunfz** [comment]
您似乎使用的是release版本，近期代码更改的比较多，但release却一直未更新。您可以尝试这个临时编译的可执行文件，看看您的问题是否仍然存在，`https://liuyunfz.lanzouf.com/i5nbO02nqlmf` 。

**Comment by FASUZO** [comment]
谢谢，已经解决。
另外我使用PyCharm，python3.9.6，源代码运行，会报一下错误

Traceback (most recent call last):
  File "D:\X\Program\py\chaoxing_tool-master\chaoxing.py", line 4, in <module>
    import json
  File "C:\Python39\lib\json\__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "C:\Python39\lib\json\decoder.py", line 11, in <module>
    import requests
  File "C:\Python39\lib\site-packages\requests\__init__.py", line 100, in <module>
    check_compatibility(urllib3.__version__, chardet_version, charset_normalizer_version)
  File "C:\Python39\lib\site-packages\requests\__init__.py", line 85, in check_compatibility
    raise Exception("You need either charset_normalizer or chardet installed")
Exception: You need either charset_normalizer or chardet installed

**Comment by liuyunfz** [comment]
您好，可以的话能请问你出现 error:Expecting value: line 1 column 1 (char 0) 错误是怎么解决的吗？因为https://github.com/liuyunfz/chaoxing_tool/issues/22 也出现了相关问题。至于你后面这个pycharm的报错，也许你可以尝试更新requests `pip install --upgrade requests`模块，它应该会自动安装上chardet 模块。

**Comment by liuyunfz** [comment]
> ![image](https://user-images.githubusercontent.com/77849230/162566485-c7931045-e5d8-44bc-9448-70eeb3f2053e.png)

您好，新版本 https://github.com/liuyunfz/chaoxing_tool/commit/d1d485236285e16c79dc988d5c00b7aee0e4854e 已尝试对该问题进行了修复，麻烦您下载最新版本再次尝试。

**Comment by FASUZO** [comment]
谢谢
