### ISSUE TITLE
课程补时长建议

### ISSUE THREAD

**Issue by abai2020** [liuyunfz/chaoxing_tool#29]
课程单独补时长只刷第一个视频，能检测该课程全部视频吗，感谢大佬

**Comment by liuyunfz** [comment]
是的，为了方便，刷取时长我默认选取了第一个视频任务点，进行重复补时长。采取这个逻辑的原因有两个：一个自然是这样写更方便；另一个则是我在课程统计平台只看到了该课程的总学习时长和各视频任务点的完成情况，不知道教师端能否详细看到各个视频的观看时长情况。
至于要加这个功能也是可行的，但可能需要一定时间，因为我近期课业较为繁忙。

**Comment by abai2020** [comment]
老师后台能看到视频时长，等大佬不忙了在看看，感谢

**Comment by TWLW9784** [comment]
刷视频时长可以单独只选择一个课程刷时长吗

**Comment by liuyunfz** [comment]
不好意思这个功能来的太迟了，最新的new分支[17f9d6e](https://github.com/liuyunfz/chaoxing_tool/commit/17f9d6e55a4f4c991756c7e69f33a78658b8f380) 已经支持了选择所有视频或者自定义视频进行时长刷取
