### ISSUE TITLE
刷取课程任务点出现JSONDecodeError

### ISSUE THREAD

**Issue by 1023386568** [liuyunfz/chaoxing_tool#30]
![image](https://user-images.githubusercontent.com/79915693/165924876-050ee8f3-4fe9-4460-a8ae-5492b827eee0.png)

**Comment by liuyunfz** [comment]
收到您的反馈了，虽然你并不需要额外开一个issue的，直接在原issue上进行回复就好了。
这个问题我周围也有一个人遇到了，他用的release版本也会出现错误，当我尝试直接用python运行的方式进行测试时却莫名顺利的全部执行成功了，于是我怀疑可能是我版本上传错了原因。
既然你仍然遇到了就让我有些摸不着头脑了，如果可以的话希望您能联系我 QQ：957843164 提供我一些更为详细的信息。再次感谢。

**Comment by 1023386568** [comment]
感谢大佬的改进！

**Comment by liuyunfz** [comment]
没事，那就是和我预料的一样了，是我release上传成旧版的了。也感谢你的反馈
