### ISSUE TITLE
有题库接口可以让他自动做题吗

### ISSUE THREAD

**Issue by fuhua666** [liuyunfz/chaoxing_tool#4]
有题库接口可以让他自动做题吗

**Comment by liuyunfz** [comment]
如果你需要的只是一个自动做题的软件，那么 油猴脚本——[超星学习通网课助手\(考试专版\)](https://greasyfork.org/zh-CN/scripts/418354-%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E7%BD%91%E8%AF%BE%E5%8A%A9%E6%89%8B-%E8%80%83%E8%AF%95%E4%B8%93%E7%89%88) 或许可以解决你的需求。然而缺憾也很明显，就是它身为油猴脚本，本身需要依赖浏览器和油猴。  
然后是正面回答你的问题，如果有题库接口，那么**理论上**是可以让本项目自动做题的，然而估计具体的实践会有一点难度，所以我也不能保证我现在的水平能写出来。

**Comment by fuhua666** [comment]
就是我的课是看一章解锁一章的，每章都有练习题，很麻烦，用这个刷的话要做一章的题刷一章解锁一章。能不能把锁着的章节视频也提前刷了呢。

**Comment by fuhua666** [comment]
> 
> 
> 如果你需要的只是一个自动做题的软件，那么 油猴脚本——[超星学习通网课助手(考试专版)](https://greasyfork.org/zh-CN/scripts/418354-%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E7%BD%91%E8%AF%BE%E5%8A%A9%E6%89%8B-%E8%80%83%E8%AF%95%E4%B8%93%E7%89%88) 或许可以解决你的需求。然而缺憾也很明显，就是它身为油猴脚本，本身需要依赖浏览器和油猴。
> 然后是正面回答你的问题，如果有题库接口，那么**理论上**是可以让本项目自动做题的，然而估计具体的实践会有一点难度，所以我也不能保证我现在的水平能写出来。

就是我的课是看一章解锁一章的，每章都有练习题，很麻烦，用这个刷的话要做一章的题刷一章解锁一章。能不能把锁着的章节视频也提前刷了呢。

**Comment by liuyunfz** [comment]
> > 如果你需要的只是一个自动做题的软件，那么 油猴脚本——[超星学习通网课助手(考试专版)](https://greasyfork.org/zh-CN/scripts/418354-%E8%B6%85%E6%98%9F%E5%AD%A6%E4%B9%A0%E9%80%9A%E7%BD%91%E8%AF%BE%E5%8A%A9%E6%89%8B-%E8%80%83%E8%AF%95%E4%B8%93%E7%89%88) 或许可以解决你的需求。然而缺憾也很明显，就是它身为油猴脚本，本身需要依赖浏览器和油猴。
> > 然后是正面回答你的问题，如果有题库接口，那么**理论上**是可以让本项目自动做题的，然而估计具体的实践会有一点难度，所以我也不能保证我现在的水平能写出来。
> 
> 就是我的课是看一章解锁一章的，每章都有练习题，很麻烦，用这个刷的话要做一章的题刷一章解锁一章。能不能把锁着的章节视频也提前刷了呢。

很抱歉，由于我并没遇到该情况，所以无法给出很确切的答案。不过按照我的猜测应该是不行的，章节被锁，相关的任务完成接口可能也就没开放，也就无法直接提前刷。

**Comment by liuyunfz** [comment]
您好，很庆幸的是这学期我遇到了您所描述的问题。结论是尽管被锁了，但还是可以通过接口获得jobid然后完成任务，我为我之前的错误猜测向您道歉。由于已过去了较长时间，我不确定您是否还需要此功能，而我暂时也不打算将此功能添加到日程中，因为我猜测这个接口很有可能被封。
如果您需要，希望您能再次联系我，我会为您提供个人的帮助。由于问题已经得到解答，我将在7天后关闭此issue，如果您还是坚持需要添加此功能，或者对我得出的结论有不同看法，也烦请您到时再次打开issue。感谢您的支持
