### ISSUE TITLE
课程处理错误

### ISSUE THREAD

**Issue by C315703603** [liuyunfz/chaoxing_tool#42]

**Comment by C315703603** [comment]
![1652854829(1)](https://user-images.githubusercontent.com/103497700/168970776-65b41f3b-07f4-4685-88f3-d9471fc570df.png)

**Comment by SongZihui-sudo** [comment]
![图片](https://user-images.githubusercontent.com/77034643/168976102-74bf0423-fa00-4cc2-9764-c552adb30ab8.png)
我这没事

**Comment by C315703603** [comment]
研究出来了，号的问题
![1652857044(1)](https://user-images.githubusercontent.com/103497700/168976922-2cef3029-0751-4f0b-a6af-d0d61ec2d8a1.png)

**Comment by SongZihui-sudo** [comment]
哦哦
