### ISSUE TITLE
无法刷取学习次数

### ISSUE THREAD

**Issue by uizidsaffd** [liuyunfz/chaoxing_tool#43]
您好，学习次数无法刷取，而且实际的运行界面与您在code中贴出来的截图不一样

**Comment by SongZihui-sudo** [comment]
的确有这个问题，刷100次，实际只有5次，你的界面什么样？

**Comment by uizidsaffd** [comment]
> 你的界面什么样？ 试了试，刷学习次数的时间间隔需要大于等于30s，才可以全刷上

还是命令行的样子，一片黑

**Comment by SongZihui-sudo** [comment]
> > 你的界面什么样？ 试了试，刷学习次数的时间间隔需要大于等于30s，才可以全刷上
> 
> 还是命令行的样子，一片黑


release 里那个时命令行的，图形界面的可执行文件还没传到 release 里。   
一种方法是 clone 源码，运行 desktop 里的 install.bat 打包成 exe  
或者也可以可以得 clone 源码，用 python 运行，desktop文件夹里的chaoxing.py。 
```
git clone https://github.com/liuyunfz/chaoxing_tool
cd chaoxing_tool
cd desktop
python chaoxing.py
```

**Comment by liuyunfz** [comment]
你好，我现在又测试了一下。学习次数是可以正常刷上的，只是当间隔较短时，实际刷取的次数与预期刷取的次数会有较大的出入，但仍然能正常的增加次数。也烦请您谅解。
故暂时关闭本issue，如果该问题还是困扰了你，也烦请继续打开本issue
