### ISSUE TITLE
视频时长重置，刚开始好好的，过几天就全没了

### ISSUE THREAD

**Issue by C315703603** [liuyunfz/chaoxing_tool#44]

**Comment by SongZihui-sudo** [comment]
#32

**Comment by C315703603** [comment]
大大，这个BUG能修复吗？

**Comment by SongZihui-sudo** [comment]
额，，，，暂时还没找到原因

**Comment by SongZihui-sudo** [comment]
> 大大，这个BUG能修复吗？

使用常规速度刷，应该不会重置，被重置的原因可能是因为用秒过时间太快了

**Comment by C315703603** [comment]
因为超星风控检测，所以我刷的时候都是按常规速度(一倍速）刷，刷的过程偶尔有些视频因为连接不到主机需要重刷，所以一个课程要重复刷3遍左右就可以把所有视频点刷完，但是大概1-2天后会视频数据返回显示没刷上，我有一个课程是这样。因为后几天以同样方法刷的还有其他课程，所以我会再看看是不是还是这样。

**Comment by SongZihui-sudo** [comment]
> 因为超星风控检测，所以我刷的时候都是按常规速度(一倍速）刷，刷的过程偶尔有些视频因为连接不到主机需要重刷，所以一个课程要重复刷3遍左右就可以把所有视频点刷完，但是大概1-2天后会视频数据返回显示没刷上，我有一个课程是这样。因为后几天以同样方法刷的还有其他课程，所以我会再看看是不是还是这样。

感谢，你也可以直接提个pr，秒过可以改成把视频先放大概30s，再秒过，不知道这样还会不会被重置。

**Comment by helloswxy** [comment]
怎么样使用当线程，1:1时长使用的是多线程，那样肯定会被重置的，我想一个视频一个刷，能不能不要所有视频同时刷

**Comment by SongZihui-sudo** [comment]
这个暂时还不行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月12日(周三) 中午1:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuyunfz/chaoxing_tool] 视频时长重置，刚开始好好的，过几天就全没了 (Issue #44)




 
怎么样使用当线程，1:1时长使用的是多线程，那样肯定会被重置的，我想一个视频一个刷，能不能不要所有视频同时刷

**Comment by liuyunfz** [comment]
> 怎么样使用当线程，1:1时长使用的是多线程，那样肯定会被重置的，我想一个视频一个刷，能不能不要所有视频同时刷

你好，相关问题的修改方案在#65 issue只有提及，可以参考一下
