### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by YoumyTheGoust** [liuyunfz/chaoxing_tool#46]
之前用都可以，现在输入密码之后回车显示“参数为空”，手打的密码，之前手打都可以，不知道这次怎么回事

**Comment by SongZihui-sudo** [comment]
![image](https://user-images.githubusercontent.com/77034643/170422091-70b73f75-47f6-40b8-b94f-ec4ffeba78b7.png)

应该是超星对密码的加密换了，用浏览器上的加密完的密码硬编码到程序里可以登录。。。。

**Comment by SongZihui-sudo** [comment]
#48
