### ISSUE TITLE
cls: command not found

### ISSUE THREAD

**Issue by fsafdrh** [liuyunfz/chaoxing_tool#47]
运行python后出现cls: command not found
手打输入账密后出现参数为空错误
运行环境：centos7.6  python3.9.13
在win11 python3.9.13同样出现参数为空错误

**Comment by SongZihui-sudo** [comment]
#46

**Comment by SongZihui-sudo** [comment]
linux 上清屏改成 `clear`,win 上是 `cls`

**Comment by SongZihui-sudo** [comment]
#48
