### ISSUE TITLE
小小反馈一下给作者大大

### ISSUE THREAD

**Issue by hongzao0316** [liuyunfz/chaoxing_tool#50]
①  完成部分课程的所有任务点功能不太会用
② 桌面版的点击登录后没有反应

**Comment by SongZihui-sudo** [comment]
1. 完成选中的课程，输入选的课程编号，回车确定，但是默认秒过。
2. 详细说一下，我这可以登录。  可以重新 pull 一下源码
![image](https://user-images.githubusercontent.com/77034643/170618488-4c821241-8c33-45f7-8f77-79b9103cb27d.png)

**Comment by hongzao0316** [comment]
1.会出现这种情况，换行后就直接换行了哈哈哈哈
2.桌面版的登录不了应该是我本地环境的问题






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 上午10:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 小小反馈一下给作者大大 (Issue #50)





  
完成选中的课程，输入选的课程编号，回车确定，但是默认秒过。
 
详细说一下，我这可以登录。  可以重新 pull 一下源码

**Comment by SongZihui-sudo** [comment]
> 1.会出现这种情况，换行后就直接换行了哈哈哈哈 2.桌面版的登录不了应该是我本地环境的问题
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "liuyunfz/chaoxing_tool" ***@***.***&gt;; 发送时间:&nbsp;2022年5月27日(星期五) 上午10:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 小小反馈一下给作者大大 (Issue #50) 完成选中的课程，输入选的课程编号，回车确定，但是默认秒过。 详细说一下，我这可以登录。 可以重新 pull 一下源码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

哦哦，是这样，按 2 进入选择，输入选择的课程序号，可以一直输入每次输入一个，按回车确认，直到输入 end ，回车结束输入（end 之前输入为选中的）。最后在回车确认就开始了。

**Comment by hongzao0316** [comment]
收到 谢谢作者！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 小小反馈一下给作者大大 (Issue #50)





  
1.会出现这种情况，换行后就直接换行了哈哈哈哈 2.桌面版的登录不了应该是我本地环境的问题
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "liuyunfz/chaoxing_tool" @.&gt;; 发送时间:&nbsp;2022年5月27日(星期五) 上午10:46 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 小小反馈一下给作者大大 (Issue #50) 完成选中的课程，输入选的课程编号，回车确定，但是默认秒过。 详细说一下，我这可以登录。 可以重新 pull 一下源码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
哦哦，是这样，按 2 进入选择，输入选择的课程序号，可以一直输入每次输入一个，按回车确认，直到输入 end ，回车结束输入（end 之前输入为选中的）。最后在回车确认就开始了。

**Comment by SongZihui-sudo** [comment]
没事
