### ISSUE TITLE
为什么登入以后获取不到课程章节呢，空白的，求解，谢谢

### ISSUE THREAD

**Issue by sexboyliu** [liuyunfz/chaoxing_tool#52]
![微信截图_20220528023402](https://user-images.githubusercontent.com/95696828/170770503-3328bf18-0fcf-4e0b-943d-2f511fc5e63c.png)
![微信截图_20220528023417](https://user-images.githubusercontent.com/95696828/170770512-99ca9699-be8e-4eba-8353-92c238704c8c.png)

**Comment by SongZihui-sudo** [comment]
> ![微信截图_20220528023402](https://user-images.githubusercontent.com/95696828/170770503-3328bf18-0fcf-4e0b-943d-2f511fc5e63c.png) ![微信截图_20220528023417](https://user-images.githubusercontent.com/95696828/170770512-99ca9699-be8e-4eba-8353-92c238704c8c.png)

不太清楚，我这可以。。。。。

**Comment by liuyunfz** [comment]
您好，可以看一下该账号的课程首页吗？可能是账号的问题。或者可以再试一下console/ 下的chaoxing.py 。由于我们这无法复现，所以暂时无法帮你解决。

**Comment by sexboyliu** [comment]
稍后哈，在上班，晚点发给你看下，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月1日(周三) 中午1:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuyunfz/chaoxing_tool] 为什么登入以后获取不到课程章节呢，空白的，求解，谢谢 (Issue #52)




 
您好，可以看一下该账号的课程首页吗？可能是账号的问题。或者可以再试一下console/ 下的chaoxing.py 。由于我们这无法复现，所以暂时无法帮你解决。

**Comment by liuyunfz** [comment]
您好，这边您一直未提供更多的信息，请问现在还是否有相关的问题呢？

**Comment by liuyunfz** [comment]
您好，由于您长期未回复本issue，故进行关闭，如有问题，您仍可再次打开本issue。谢谢
