### ISSUE TITLE
打包编译后出现模块缺失

### ISSUE THREAD

**Issue by NAILIANGCHI** [liuyunfz/chaoxing_tool#53]
无法使用
编译为console后打开闪退
编译为desktop后提示缺少pydes模块
报错信息：Traceback (most recent call last):
  File "chaoxing.py", line 13, in <module>
ModuleNotFoundError: No module named 'pyDes'
![image](https://user-images.githubusercontent.com/85297838/170812221-8f86c108-0580-4d55-a6d4-7179b73b0ec2.png)

**Comment by SongZihui-sudo** [comment]
#48 更新加入了一个新包。  
```
pip install pyDes
```

**Comment by NAILIANGCHI** [comment]
这是来自QQEmail的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
