### ISSUE TITLE
登录不进去，程序秒退了

### ISSUE THREAD

**Issue by hongzao0316** [liuyunfz/chaoxing_tool#55]
![image](https://user-images.githubusercontent.com/80839171/171200849-62c925dc-d066-4010-987f-51bf51ed658d.png)

**Comment by SongZihui-sudo** [comment]
不太清楚原因。。。。。

**Comment by hongzao0316** [comment]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='passport2.chaoxing.com', port=443): Max retries exceeded with url: /fanyalogin (Caused by ProxyError('Your proxy appears to only use HTTP and not HTTPS, try changing your proxy URL to be HTTP. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#https-proxy-error-http-proxy', SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1076)'))))
这应该是比较关键的报错了 希望作者大大有时间看一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 凌晨0:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 登录不进去，程序秒退了 (Issue #55)





 
不太清楚原因。。。。。

**Comment by liuyunfz** [comment]
可以检查一下是否启用了VPN等转发工具。

**Comment by hongzao0316** [comment]
确实是 用了github加速的软件代理导致的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 登录不进去，程序秒退了 (Issue #55)





 
可以检查一下是否启用了VPN等转发工具。

**Comment by liuyunfz** [comment]
那现在解决了吗？如果解决了的话麻烦关闭此issue吧

**Comment by hongzao0316** [comment]
收到 感谢耐心的作者 嘿嘿




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 下午2:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] 登录不进去，程序秒退了 (Issue #55)





 
那现在解决了吗？如果解决了的话麻烦关闭此issue吧
