### ISSUE TITLE
登陆后显示“课程处理失败，请联系作者”

### ISSUE THREAD

**Issue by YoumyTheGoust** [liuyunfz/chaoxing_tool#59]
同标题

**Comment by SongZihui-sudo** [comment]
我这没遇到这个问题，能不能详细说明下

**Comment by SongZihui-sudo** [comment]
![image](https://user-images.githubusercontent.com/77034643/191009046-f98baf59-35ac-4de9-a660-1fc21e3075c0.png)
![image](https://user-images.githubusercontent.com/77034643/191009106-dd25ec47-c0b1-4ac3-834b-769b411771f9.png)
