### ISSUE TITLE
请问有没有可能单线程一个视频一个视频得看

### ISSUE THREAD

**Issue by 19819068211** [liuyunfz/chaoxing_tool#64]
请问有没有可能单线程一个视频一个视频得看

**Comment by SongZihui-sudo** [comment]
可以改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月13日(周四) 晚上9:12
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [liuyunfz/chaoxing_tool] 请问有没有可能单线程一个视频一个视频得看 (Issue #64)




 
请问有没有可能单线程一个视频一个视频得看
