### ISSUE TITLE
怎么单线程一个视频一个视频去看

### ISSUE THREAD

**Issue by 2682856025** [liuyunfz/chaoxing_tool#65]
想用dev分支 但是还是多线程 怎么改成单线程

**Comment by SongZihui-sudo** [comment]
在这个自定义任务类里添加任务




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月14日(星期五) 晚上6:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[liuyunfz/chaoxing_tool] 怎么单线程一个视频一个视频去看 (Issue #65)





 
想用dev分支 但是还是多线程 怎么改成单线程

**Comment by 19819068211** [comment]
请问如何修改可以由多线程同的进行一个线程一个线程的运行

**Comment by liuyunfz** [comment]
您好，多线程的调起在源代码的921行
```python
for i in threadPool:
    i.start()
    time.sleep(10)
for j in threadPool:
    j.join()
```
所以理论修改为
```python
for i in threadPool:
    i.start()
    i.join()
```
实现在前一个线程执行完成后再启动下一个线程

**Comment by 19819068211** [comment]
同理，第785行
for item in video_nomal_thread_pool:
可能也应该注释掉，测试过可以了
