### ISSUE TITLE
怎么使用end退出

### ISSUE THREAD

**Issue by q51005522555225** [liuyunfz/chaoxing_tool#68]
选部分课程输入end不能用

**Comment by liuyunfz** [comment]
![image](https://user-images.githubusercontent.com/46259392/198962924-ff4c310e-ceda-49ce-aa22-d8d29b6cebc4.png)
您好，经过最新测试，功能可以正常使用。请注意，每个课程序号和end都需要以回车进行分隔

**Comment by liuyunfz** [comment]
您好，由于您长期未给出新的答复，特此关闭issue。如果您还有上述问题，烦请您再次打开并提供更多详细信息，谢谢。
