### ISSUE TITLE
打开输入手机号和密码后就闪退，反复测试仍这样

### ISSUE THREAD

**Issue by ABC793478** [liuyunfz/chaoxing_tool#69]

**Comment by liuyunfz** [comment]
你好，请问你使用的是源文件还是release里的编译文件。如果是前者，请检查requirements里的依赖是否都已经安装。如果是后者请检查是否下载的是最新的pre-release版本，而不是稳定的1.6版本

**Comment by ABC793478** [comment]
用的是release里面的exe单独执行，是最新版，还是输入完后闪过很多信息然后自己关闭了窗口。

**Comment by liuyunfz** [comment]
您还可以检查一下是否开了vpn等网络代理

**Comment by ABC793478** [comment]
介绍页写了是解压release中的disk，但release没有找到，只有exe文件，我就下载了那个。
也许是有vpn原因。
我后来用命令行（方案一）就可行了~

**Comment by liuyunfz** [comment]
感谢提醒，因为原本的release是一个压缩包，exe文件在其中的dist目录，后来修改为单文件了但没有及时修改README文件。至于vpn问题因为我之前测试时有遇到过相关情形，所以大概率是这个原因了。

**Comment by ABC793478** [comment]
OK，谢谢回复。
