### ISSUE TITLE
已结课的课程处理问题

### ISSUE THREAD

**Issue by liuyunfz** [liuyunfz/chaoxing_tool#7]
针对已结课的课程，目前无法正确获得其章节内容。可能带来的影响是无法下载其资源，但因为已结课所以对完成任务节点这个功能并无影响。目前已知该问题，但修复暂未提上日程。

**Comment by NAILIANGCHI** [comment]
> 针对已结课的课程，目前无法正确获得其章节内容。可能带来的影响是无法下载其资源，但因为已结课所以对完成任务节点这个功能并无影响。目前已知该问题，但修复暂未提上日程。
正遇见此问题，，希望可以对已完成的视频任务再次常规播放来解决视频时间不够的问题，本想自己解决但是尝试无果希望作者可以添加内容，另外刷取视频时间那个功能貌似失效，可以参考我所提出的问题来改变刷去视频次数的功能🥰

**Comment by liuyunfz** [comment]
> 

你好，由于前段时间一直较为忙碌，所以并未对相关问题进行审查和对您进行回复。近段时间，相关刷取视频时长功能错误的问题不断被提出，这才得已抽空进行了修复。现在 https://github.com/liuyunfz/chaoxing_tool/commit/62024887dbe937c05dacd653d4b3170a45249aef 版本已对该功能进行了修复尝试，并在本地测试成功，还望您更新至最新版本进行尝试。
此外，您提到的`对已完成的视频任务再次常规播放来解决视频时间不够的问题`就是我开发刷取视频时间这个功能的初衷，现在这个功能已经修复【大概】，那么您的需求应该也就得到了解决，如果您还有问题也欢迎继续回复我。
另外额外提一句，如果是限定于本issue下的话，现在的超星逻辑似乎是已结束的课程无法再刷取时长了。

**Comment by NAILIANGCHI** [comment]
已测试可以使用，感谢作者抽出时间修复程序🥰

**Comment by NAILIANGCHI** [comment]
这是来自QQEmail的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
