### ISSUE TITLE
部分课程 包响应 "isPassed":flase

### ISSUE THREAD

**Issue by GlowXuthusFly** [liuyunfz/chaoxing_tool#70]

**Comment by liuyunfz** [comment]
请问你使用是立即完成吗？可以尝试使用同倍速完成试试

**Comment by liuyunfz** [comment]
根据最新的逻辑，如果视频或音频开启了防拖拽，则需要使用同倍速刷取。尽管如此，您仍可以同步刷取所有视频，即所需时长为最长视音频的总长。

**Comment by liuyunfz** [comment]
您好，由于您长期未给出新的答复，特此关闭issue。如果您还有上述问题，烦请您再次打开并提供更多详细信息，谢谢。
