### ISSUE TITLE
什么时候能刷mp3的

### ISSUE THREAD

**Issue by q51005522555225** [liuyunfz/chaoxing_tool#71]
什么时候能刷mp3的

**Comment by liuyunfz** [comment]
感谢督促，已经写好了，今天晚点就上线

**Comment by liuyunfz** [comment]
最新的commit已更新，烦请您有空的话进行一下测试

**Comment by liuyunfz** [comment]
您好，由于您长期未给出新的答复，特此关闭issue。如果您还有上述问题，烦请您再次打开并提供更多详细信息，谢谢。
