### ISSUE TITLE
能不能批量刷次数，

### ISSUE THREAD

**Issue by q51005522555225** [liuyunfz/chaoxing_tool#73]
一个号选多门刷次数

**Comment by Helblau6** [comment]
怎么我运行的时候说少一个pyDes

**Comment by liuyunfz** [comment]
> 一个号选多门刷次数

可以的，但是暂时没有更新的打算。因为类似的批量操作可以衍生很多，或者加上多线程功能。但是由于项目编写初期的遗留问题，添加功能十分复杂且冗余。您可以尝试fork仓库后自己进行修改，给您带来的不便，多请谅解。

**Comment by LYL-TYR412** [comment]
> 一个号选多门刷次数

希望能增加做题的功能

**Comment by liuyunfz** [comment]
> > 一个号选多门刷次数
> 
> 希望能增加做题的功能

这个写起来会很麻烦，而且需要题库。您可以使用现成的油猴脚本。
