### ISSUE TITLE
下载代码运行的时候怎么说少一个pyDes

### ISSUE THREAD

**Issue by Helblau6** [liuyunfz/chaoxing_tool#75]

**Comment by Helblau6** [comment]
下载代码运行的时候怎么说少一个pyDes

**Comment by liuyunfz** [comment]
项目是有依赖pyDes，请检查是否在使用前安装了所需依赖 `pip install -r requirements`

**Comment by Helblau6** [comment]
输入命令符也添加不进去啊

**Comment by liuyunfz** [comment]
> 输入命令符也添加不进去啊
> 

如果无法通过requirements.txt文件进行安装可以尝试直接pip安装，使用`pip install pyDes`
如果仍然不行可以尝试直接下载release版本
