### ISSUE TITLE
不能学校登录吗？

### ISSUE THREAD

**Issue by TWLW9784** [liuyunfz/chaoxing_tool#79]
可以添加学校登录吗？这样实用性更强

**Comment by liuyunfz** [comment]
可以添加的，麻烦请提供一个学校登录的网址。

**Comment by TWLW9784** [comment]
https://github.com/liuyunfz/chaoxing_tool/issues/79#issuecomment-1452878588
感谢

**Comment by liuyunfz** [comment]
你好，针对你的要求已经对最新版添加了Cookie登录的功能。由于近期我在重构本项目，故现在项目只属于修补的状态，没有添加显著feature的打算。您所需要的机构登录由于涉及验证码，也需要一些繁琐的代码，故没有直接从根源添加。
下面是使用Cookie登录的教程：
首先，你可以在任意PC端的浏览器登录超星，然后访问 http://i.chaoxing.com/ 
随后，打开浏览器的开发者人员工具，找到网络（Network）选项，保持开启，然后刷新网页。
![image](https://user-images.githubusercontent.com/46259392/222626386-26e187e1-9ed6-4800-a644-a304aad0217c.png)
之后，你会获得一系列的包，将滑块拉至顶部，找到第一个并点击
![image](https://user-images.githubusercontent.com/46259392/222626522-e2084132-5592-4ff0-88d0-577b2481367a.png)
然后下拉找到请求标头-Cookie
![image](https://user-images.githubusercontent.com/46259392/222626612-242e0a7e-1831-4975-8f87-f798409c9e6a.png)
将cookie：后面的内容复制，即是软件需要的cookie。然后在该串字符中找到_uid选项，后面的数字即是程序需要的uid。
至此便完成了cookie登录

**Comment by liuyunfz** [comment]
您已较长时间未回复，由于已给出了解答，故关闭本issue。如果您还有相关问题请继续提出并重新打开
