### ISSUE TITLE
能加个常规速度吗

### ISSUE THREAD

**Issue by Hentai02** [liuyunfz/chaoxing_tool#8]
正常观看视频的速度完成任务点。太快有点不合理

**Comment by liuyunfz** [comment]
收到，我在超星的新版教师后台看到了有关时长与倍速导致的异常问题。正常倍速观看功能已加入日程，请您静候我的更新

**Comment by Hentai02** [comment]
静候佳音

**Comment by liuyunfz** [comment]
你好，你所需要的功能已在目前最新的 1e88450 版本进行了添加。目前功能2会使用多线程对多个视频进行同时的1倍速完成模拟。而功能1仍会立即完成视频任务点，你可以根据需求进行选择。

**Comment by liuyunfz** [comment]
如果有问题的话欢迎您重新打开本issue
