### ISSUE TITLE
课程资源无法下载,且建议添加一个一键下载选中课程全部资源

### ISSUE THREAD

**Issue by Cjiio** [liuyunfz/chaoxing_tool#80]

**Comment by liuyunfz** [comment]
你好，master版本的我不确定。如果你可以使用python环境，推荐你试一下new分支下的项目。
里面也支持一键下载当前课程的全部资源

**Comment by Cjiio** [comment]
我无法运行new分支下的项目,貌似 requirements.txt下依赖并不完整

**Comment by liuyunfz** [comment]
> 我无法运行new分支下的项目,貌似 requirements.txt下依赖并不完整,无yaml模块,应该添加pyyaml

感谢您的提醒，经过测试确实缺少了yaml包的依赖说明，麻烦先手动`pip install PyYAML`以使项目正常运行，下一个版本我会修复它

**Comment by liuyunfz** [comment]
new分支已经提交了新版，完善了requirements文件和下载中的全选下载所有资源，还烦请你更新后测试一下了。但不保证能下载所有文件，部分文件会出现id获取错误的问题

**Comment by Cjiio** [comment]
能给个联系方式吗?后续有Bug方面的问题和python技术交流问题方便讨论

**Comment by liuyunfz** [comment]
> 能给个联系方式吗?后续有Bug方面的问题和python技术交流问题方便讨论

好的，这是我的QQ:`957843164`

**Comment by Cjiio** [comment]
已经添加,感谢
