### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by woshineide** [liuyunfz/chaoxing_tool#81]
输入完密码回车闪退，python环境已经配置

**Comment by liuyunfz** [comment]
你好，想请问下你用的上release版本还是源文件版本呢？
如果是后者，并且环境配置没有问题的话可以检查下网络是否出现了问题，比如说挂了vpn这种

**Comment by liuyunfz** [comment]
您已较长时间未回复本issue，鉴于已给出解决方案已经本地并未出现该问题的复现，故关闭此issue。如果你还有相关问题欢迎继续提供更详细的信息并重新打开本issue。
