### ISSUE TITLE
new分支，刷视频总是失败

### ISSUE THREAD

**Issue by SongZihui-sudo** [liuyunfz/chaoxing_tool#83]
![image](https://user-images.githubusercontent.com/77034643/227982607-304b1b11-1cdc-42a1-b2fe-e669dac88b3d.png)

**Comment by liuyunfz** [comment]
这个我有遇到过，我试过用master分支，发现如果使用的是立即完成也会出现未完成的情况，似乎这种只能等时长刷取

**Comment by SongZihui-sudo** [comment]
哦哦获取Outlook for Android发件人: ***@***.*** ***@***.***> 代表 liuyunfz ***@***.***>发送时间: 2023年3月27日星期一 下午11:32收件人: chaoxing_tool ***@***.***>抄送: 1751122876 ***@***.***>; author ***@***.***>主题: Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)
是的，因为new分支还处于开发阶段，只完成了基本的功能，一些可选的选项还没完善，暂时只能一键完成

**Comment by liuyunfz** [comment]
最新的分支已经支持通过配置文件中的设置来选择立即完成与等时长完成了，还烦请你有空的时候可以试试，然后关闭此issue

**Comment by SongZihui-sudo** [comment]
👌，好的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 晚上9:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)




 
最新的分支已经支持通过配置文件中的设置来选择立即完成与等时长完成了，还烦请你有空的时候可以试试，然后关闭此issue

**Comment by SongZihui-sudo** [comment]
登录的时候，崩掉了

配置文件是默认的



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上9:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)





 
最新的分支已经支持通过配置文件中的设置来选择立即完成与等时长完成了，还烦请你有空的时候可以试试，然后关闭此issue

**Comment by liuyunfz** [comment]
我这边拉取了最新的文件并在本地虚拟环境上运行是没问题的欸

**Comment by liuyunfz** [comment]
您可以检查一下是否开启了clash等此类代理软件，导致ProxyError的报错

**Comment by SongZihui-sudo** [comment]
有的成功，有的不成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上10:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)





 
我这边拉取了最新的文件并在本地虚拟环境上运行是没问题的欸

**Comment by liuyunfz** [comment]
将config.yml文件中的video-mode设置为1后开启等时长刷取，等待对应时长后应该所有的视频任务点都会成功完成。是出现了类似20分钟视频刷了20分钟后仍没有成功的情况吗

**Comment by SongZihui-sudo** [comment]
我看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)





 
将config.yml文件中的video-mode设置为1后开启等时长刷取，等待对应时长后应该所有的视频任务点都会成功完成。是出现了类似20分钟视频刷了20分钟后仍没有成功的情况吗

**Comment by SongZihui-sudo** [comment]
等了挺长时间




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上10:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)





 
将config.yml文件中的video-mode设置为1后开启等时长刷取，等待对应时长后应该所有的视频任务点都会成功完成。是出现了类似20分钟视频刷了20分钟后仍没有成功的情况吗

**Comment by liuyunfz** [comment]
不是不是，我的意思就是你改一下配置文件，然后改成等时长刷取。这时候程序应该会启动一个与视频时长相等的线程，等程序运行完毕提示刷取完成，应该任务点也就完成了

**Comment by SongZihui-sudo** [comment]
等了一会，最后成功了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 晚上11:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)




 
不是不是，我的意思就是你改一下配置文件，然后改成等时长刷取。这时候程序应该会启动一个与视频时长相等的线程，等程序运行完毕提示刷取完成，应该任务点也就完成了

**Comment by liuyunfz** [comment]
既然没有问题，那本issue就关闭了

**Comment by SongZihui-sudo** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyunfz/chaoxing_tool"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月30日(星期四) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [liuyunfz/chaoxing_tool] new分支，刷视频总是失败 (Issue #83)





 
既然没有问题，那本issue就关闭了
