### ISSUE TITLE
new分支，有的任务点不支持

### ISSUE THREAD

**Issue by SongZihui-sudo** [liuyunfz/chaoxing_tool#85]
![image](https://user-images.githubusercontent.com/77034643/229957690-af593bb4-2420-4068-8dfc-332d46333335.png)
![image](https://user-images.githubusercontent.com/77034643/229957844-49b73b6e-ea01-40b8-8221-4b09b1979c30.png)
![image](https://user-images.githubusercontent.com/77034643/229957874-a6c636d2-1f84-456a-a7bf-34fc9cd766cb.png)

**Comment by liuyunfz** [comment]
这个是章节测试这种嘛？就是习题那种
如果是的话应该暂时没有适配的打算

**Comment by SongZihui-sudo** [comment]
> 这个是章节测试这种嘛？就是习题那种 如果是的话应该暂时没有适配的打算

可能那些是题，但是视频就是开了等时长刷，读完所有视频，最后会功能调用失败，用旧版的等时长可以刷。

**Comment by liuyunfz** [comment]
你好，针对以上问题。
1. workId 的任务点暂不支持完成，且没有完成打算
2. Live 任务点接口似乎已经更换，最新commit已更新修复，还烦请测试
3. 针对图2的错误是突然的网络错误导致程序信息获取失败，后续步骤无法顺利执行。重新尝试即可

综上，感谢您的反馈。如果上述问题都得到了解决也请记得关闭本issue，或者继续在下方与我交流，谢谢。

**Comment by SongZihui-sudo** [comment]
> 你好，针对以上问题。
> 
> 1. workId 的任务点暂不支持完成，且没有完成打算
> 2. Live 任务点接口似乎已经更换，最新commit已更新修复，还烦请测试
> 3. 针对图2的错误是突然的网络错误导致程序信息获取失败，后续步骤无法顺利执行。重新尝试即可
> 
> 综上，感谢您的反馈。如果上述问题都得到了解决也请记得关闭本issue，或者继续在下方与我交流，谢谢。

应该可以了
