### ISSUE TITLE
期待加入需完成90%观看的直播任务点刷取

### ISSUE THREAD

**Issue by 19819068211** [liuyunfz/chaoxing_tool#86]
![image](https://user-images.githubusercontent.com/66981884/230896912-d1fedbff-0efa-43f8-868b-39fff655e4b7.png)

**Comment by liuyunfz** [comment]
该内容已在最新的commit https://github.com/liuyunfz/chaoxing_tool/commit/abde6d23507defdd46d130124917ba26a1ebd795 中进行了提交。还烦请方便的话可以测试一下

**Comment by liuyunfz** [comment]
由于您较久未回复，且已为您的问题作出了解答，故关闭本issue。如果您还有相关问题烦请再次打开
