### ISSUE TITLE
阿里云服务器挂这个，一直重定向失败

### ISSUE THREAD

**Issue by TheWuSi** [liuyunfz/chaoxing_tool#88]
dns设置跟我电脑一样的，我电脑正常，服务器就一直重定向

**Comment by liuyunfz** [comment]
以前我记得在阿里云上试过，好像是阿里云把超星ip屏蔽了还是超星把阿里云的ip屏蔽了。你可以不用软件测试一下访问超星的一些地址，或者直接在本地计算机跑本程序
