### ISSUE TITLE
为什么我选择等时常刷取的配置文件还是秒刷。。

### ISSUE THREAD

**Issue by 1642414488** [liuyunfz/chaoxing_tool#90]

**Comment by liuyunfz** [comment]
因为配置文件不是热读取，而是在程序载入时进行一次性读取。修改后需要重新运行程序才行

**Comment by 1642414488** [comment]
我确实是重新运行了一遍程序，但是还是秒刷取。

**Comment by liuyunfz** [comment]
您可以再次检查下是否修改的是程序根目录下config.yml文件中的video-mode值为1，并进行了保存。程序关闭后重新进行了运行。
代码逻辑应该并没有问题，我这边测试也是没问题的呢

**Comment by 1642414488** [comment]
![image](https://github.com/liuyunfz/chaoxing_tool/assets/20734339/dae5ed76-d80f-41ae-82b2-db59c75c1011)

**Comment by liuyunfz** [comment]
![image](https://github.com/liuyunfz/chaoxing_tool/assets/46259392/39ee037e-9e80-4204-9580-b02ad147a5a5)
您的修改并没有问题，我也不知道错误发生在了哪里，您可以尝试重新拉取最新版试试

**Comment by 1642414488** [comment]
我换那个master版本了 但是提示我ModuleNotFoundError: No module named 'yaml'，我的ymal用pip在cmd里安装了的

**Comment by liuyunfz** [comment]
既然提示没有那您可以尝试重新再安装试试，pip install PyYAML
又或者您使用了虚拟环境或者多个python版本

**Comment by 1642414488** [comment]
解决了 我在pycharm里又安装了一遍包，现在可以使用了，但是好像运行速度有点慢？

**Comment by 1642414488** [comment]
解决了 我用控制台就会速度快很多，用pycharm就感觉卡卡的

**Comment by 1642414488** [comment]
但是好像还是秒刷。

**Comment by 1642414488** [comment]
我的代码里好像没有 if self.video这个 main.py里没看到

**Comment by liuyunfz** [comment]
> 我的代码里好像没有 if self.video这个 main.py里没看到

是在functions/deal_mission.py文件里

**Comment by 1642414488** [comment]
可以了 已经解决了，很感谢您

**Comment by liuyunfz** [comment]
不客气的
