### ISSUE TITLE
有的在终端里显示刷完了，但是并没有刷上

### ISSUE THREAD

**Issue by 1642414488** [liuyunfz/chaoxing_tool#91]
我大概是刷一门课刷了三遍，每次都是35/127，刷不完整。

**Comment by 1642414488** [comment]
我使用的是等时常刷取

**Comment by liuyunfz** [comment]
大概率跟这个是一样的问题https://github.com/liuyunfz/chaoxing_tool/issues/92

**Comment by 1642414488** [comment]
可能是，感觉很多课都刷不上时常。

**Comment by liuyunfz** [comment]
合并并关闭同类issue，最新进展详见https://github.com/liuyunfz/chaoxing_tool/issues/92
