### ISSUE TITLE
输入密码时完全隐藏不可见，  感觉有点不适 ，可以改为显示******

### ISSUE THREAD

**Issue by shan869** [liuyunfz/chaoxing_tool#93]
```python
import msvcrt
import getpass

def getpass_with_mask(prompt="Password: "):
    password = ""
    sys.stdout.write(prompt)
    sys.stdout.flush()
    while True:
        char = msvcrt.getch()
        if char == b'\r' or char == b'\n':
            break
        elif char == b'\x08':
            if len(password) > 0:
                password = password[:-1]
                sys.stdout.write("\b \b")
                sys.stdout.flush()
        else:
            password += char.decode("utf-8")
            sys.stdout.write("*")
            sys.stdout.flush()
    sys.stdout.write("\n")
    return password

password = getpass_with_mask("请输入您的密码: ")

```

**Comment by SongZihui-sudo** [comment]
你可以fork一下仓库，然后提一个pull request



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月21日(周日) 上午10:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [liuyunfz/chaoxing_tool] 输入密码时完全隐藏不可见，  感觉有点不适 ，可以改为显示****** (Issue #93)




 
import msvcrt
 import getpass
 
def getpass_with_mask(prompt="Password: "):
 password = ""
 sys.stdout.write(prompt)
 sys.stdout.flush()
 while True:
 char = msvcrt.getch()
 if char == b'\r' or char == b'\n':
 break
 elif char == b'\x08':
 if len(password) &gt; 0:
 password = password[:-1]
 sys.stdout.write("\b \b")
 sys.stdout.flush()
 else:
 password += char.decode("utf-8")
 sys.stdout.write("*")
 sys.stdout.flush()
 sys.stdout.write("\n")
 return password
 
password = getpass_with_mask("请输入您的密码: ")

**Comment by liuyunfz** [comment]
您好，感谢您曾经的提议，由于现在新的重构代码已无密码隐藏（过多人反映加上额外模块导入），故将本enhancement关闭。如果您仍有更好的方案欢迎提交pr
