### ISSUE TITLE
无法刷取学习次数

### ISSUE THREAD

**Issue by 35erihei** [liuyunfz/chaoxing_tool#94]
ERROR | utils:doGet:39 - Get Url https://stat2-ans.chaoxing.com/stat2/task/s/index?courseid=207017040&cpi=215414922&clazzid=77698520&ut=s& Error
 Url: https://stat2-ans.chaoxing.com/stat2/task/s/index?courseid=207017040&cpi=215414922&clazzid=77698520&ut=s&
Method: Get
Status: 403
不知道为甚末

**Comment by liuyunfz** [comment]
该链接指向的是课程的学习记录页面，我这边测试了下从教师端关闭学生的学习记录导航也仍然可以访问，所以暂时不知道为什么会出现403错误。
您可以试试手动从网页端进行查看，看能否查看自己的学习记录情况，如果您想跳过该错误直接刷取可以修改`classis/Course/__init__.py`文件中第128-133行
`python
        # _url = f"https://stat2-ans.chaoxing.com/stat2/task/s/index?courseid={self.course_id}&cpi={self.cpi}&clazzid={self.class_id}&ut=s&pEnc={self.jobEnc}&"
        # _rsp = doGet(url=_url, headers=self.headers)
        # _ele = etree.HTML(_rsp)
        # _acc = xpath_first(_ele, "//div[@class='fl min']/span/text()")
        # _all = re.findall(r'总时长 (\d+)', _rsp)[0]
        return [0.0, 10.0]
```
其中10.0为您想要刷取的分钟数

**Comment by liuyunfz** [comment]
不好意思，又看了一眼您的报错信息。发现您请求的链接似乎是之前版本的遗留错误，该错误已在863e1cf中进行了更正修复，烦请您更新一下代码后再试试。
如果您使用的是release版本，需要再等一段时间推出正式版

**Comment by liuyunfz** [comment]
最新release已更新，修复了该问题。https://github.com/liuyunfz/chaoxing_tool/releases/tag/v2.1
如果您还遇到了该问题请重新打开本issue
