### ISSUE TITLE
get_chapter报错

### ISSUE THREAD

**Issue by lkf2432** [liuyunfz/chaoxing_tool#95]
![代码中报错位置](https://github.com/liuyunfz/chaoxing_tool/assets/48993944/1c7f0539-25bc-488c-93f1-52260a43d8fe)
![html文件](https://github.com/liuyunfz/chaoxing_tool/assets/48993944/4a4641f7-2c2f-4960-90ce-22e36c509106)
图1为代码报错位置
图2为html文件报错位置截图
排查可能是因为图2中②处为未解锁的任务点，所以没有已解锁任务点（如①处）的onclick属性，所以报错了
以下是html_text压缩文件
[new 3.zip](https://github.com/liuyunfz/chaoxing_tool/files/11546757/new.3.zip)

**Comment by lkf2432** [comment]
> 你可以把下标改成2试一下，可以提一个pull request 过来

**Comment by liuyunfz** [comment]
> 下标改成2也是取不到吧，因为未解锁的任务点压根就没有onlick属性。而如何获取有onclick属性的未解锁任务点的html我也不知道。。。

您说的没错，目前的是预期做法是将该值置空，并额外设置一个可访问标记。这个特征将在下次进行添加，如果有需要您可以在这里加入try except语句以避免报错导致的程序无法执行

**Comment by liuyunfz** [comment]
您好，该bug已在最新的的提交中https://github.com/liuyunfz/chaoxing_tool/commit/cbbb0def771e3141cd9783ab34c68274676f57ec 进行了修复。还烦请您进行测试
另外，由于海象运算符的引入，需要python3.8及以上的支持，该内容之后会在readme文件中进行更新说明
